spring.application.name=api
server.port=8080

spring.datasource.url=jdbc:postgresql://ep-solitary-moon-aqb60aj1-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_QdKUC6PNHhV9
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Custom JWT configuration
jwt.secret=8c98355b83cadcf082b10a72d039d5f491c0f5bfe7e82a6c228013a8e2984867b9a87fd248466188c69959ebe8f50f67014edf9cc2141cc85c49b894a905944b
jwt.expirationMs=31536000000
